### ISSUE TITLE
MM 2.2.0 No metadata

### ISSUE THREAD

**Issue by kdmarchuk** [henrypinkard/Pygellan#16]
Using the demo config for acquisitions and explore, no XML metadata file is produced.

**Comment by henrypinkard** [comment]
You mean the FIJI_BigDataViewer_Metadata.xml file? I took this out because it no longer had a function

**Comment by kdmarchuk** [comment]
Imaricumpiler is crashing on test datasets. FIJI has been recently updated. I had assumed it was the lack of xml. 

Can't find display settings in file: test_MagellanStack.tif
Num channels tag missiing
java.lang.RuntimeException
  at org.micromanager.plugins.magellan.misc.MD.getNumChannels(MD.java:563)
  at org.micromanager.plugins.magellan.imagedisplay.DisplaySettings.getDisplaySettingsFromSummary(DisplaySettings.java:46)
  at org.micromanager.plugins.magellan.acq.TaggedImageStorageMultipageTiff.processSummaryMD(TaggedImageStorageMultipageTiff.java:113)
  at org.micromanager.plugins.magellan.acq.TaggedImageStorageMultipageTiff.setSummaryMetadata(TaggedImageStorageMultipageTiff.java:390)
  at org.micromanager.plugins.magellan.acq.TaggedImageStorageMultipageTiff.openExistingDataSet(TaggedImageStorageMultipageTiff.java:167)
  at org.micromanager.plugins.magellan.acq.TaggedImageStorageMultipageTiff.<init>(TaggedImageStorageMultipageTiff.java:91)
  at MM.MMDataset.<init>(MMDataset.java:163)
  at pipeline.God.fileToLoadedMMData(God.java:108)
  at pipeline.God$2.run(God.java:128)
  at java.lang.Thread.run(Thread.java:748)
 
Num channels tag missiing

**Comment by henrypinkard** [comment]
This is neither a bug in Pygellan nor Magellan. I removed that metadata tag a couple months ago when doing a refactor to make acquisitions more flexible with respect to channels. You no longer know the number of channels in advance, rather they are just added at runtime. This allows for on the fly adding and deleting of channels, a necessary modification for flexible acquisition control I will add in future versions. 

This means that the imaricumpiler source code would need to be updated to read the number of channels directly from the image tags. There is a [new function](https://github.com/henrypinkard/micro-manager/blob/cee0bde92534bcb696173ad57d3afe04beefaa89/plugins/Magellan/src/main/java/org/micromanager/magellan/datasaving/TaggedImageStorageMultipageTiff.java#L109) that provides the same information that you would need replace the offending line (MMDataset.java:163) with.
