### ISSUE TITLE
MM 2.2.0 Can't add acquisitions

### ISSUE THREAD

**Issue by kdmarchuk** [henrypinkard/Pygellan#17]
The "+" button on the acquisitions tab does not add another line for multiple acquisitions.

Can we also get an example of how to add an acquisition in python? something like?
```
acquisitions = magellan.get_acquisitions()
acq = acquisitions[0]
acq_settings = acq.get_acquisition_settings()

acq1 = acq
acquisitions.append(acq1)
```

**Comment by kdmarchuk** [comment]
Also, 

```
bridge = MagellanBridge()
magellan = bridge.get_magellan()
core = bridge.get_core()

acquisitions = magellan.get_acquisitions()
```
Produces the error in PyCharm
Exception ignored in: <function MMJavaClass.__del__ at 0x00000000036BAEA0>
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pygellan\acquire.py", line 145, in __del__
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\sugar\socket.py", line 395, in send
  File "zmq/backend/cython/socket.pyx", line 725, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 766, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 135, in zmq.backend.cython.socket._check_closed
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\error.py", line 37, in __init__
ImportError: sys.meta_path is None, Python is likely shutting down

Might be related?

**Comment by henrypinkard** [comment]
Fixed buttons on the GUI and modified example to show adding acq: https://github.com/henrypinkard/Pygellan/blob/master/examples/create_and_run_acquisition.py

These changes depend on a PR on micro-manager side: https://github.com/nicost/micro-manager/pull/71

Wasn't able to reproduce error in your second comment. I think this may be from a bug in an older version. Let me know if you see this again and can reproduce it
